language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Iv870PTPhfEWS0haPFjFjlUdT0URhCfIgDbuJfWbx7T8C78FinLqv4OMOgM1pgA7UBzZIGxsgUA198JBcM//k9AKJWoEO1Sm/kxNsQfc2Bki+TpdXi4RdqOsOm6JxufWv+bbnJ9kINgXrkskTB9zJ0OQDtlZuyP/re2k6QML8tJpnfuh9/EVJ4hR0GQLy5weHY5Tc1dnEB0/kaOazvP9rJB5uzDtiQXM/vjYIJQd2txqM5GEXTJvPztdGLkSNoayBNTcd3AtuYChT0k7srwCLEas1Dk8lWQ6ryjQJtZCzy27862JXkJzQgODq4gP/zvGLj+lzdumryCTk/1ZQ+BHDJjJHyUo6+gsIvabbq7pfLcuB94LyzARaJEH0p1HztBzFYus8mDgWO+2RiUS8GM7Yvz4MA05oP6NMtJMyO59ppC4WrPoNNA8r4Jvp451LcyfP/phpqOi4Sp/edpzw90qjBt9vhcV5JyM9xbekcyB/m8bWM0bjlD7vKbZ4mv3JnRonEwpYcJxJE4dlVbULHy9RRHjuXEddpoBjJ1y4ClRb0YvarpS1ll6wzC6KTYyC4m+wFdRa4PUVq1xJ4KqHt4JozVIi3O4XJ+Stb8Q7u9Hvm2xQOPpr1Ettq8WjoMXFgWKNqSl+aIAIR9a/PLsgBk7uHHA08sfpoybYCQlBFe+X3w=
  app: afternoon-brushlands-67926
  on:
    repo: escottalexander/house-flip-tools-server
