language: node_js
node_js: node
services:
- postgresql
before_script:
- psql -c 'create database house-flip-tools-test-db;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: wa+m8ZZxRByfvk5+sWkPYdSP8pVk6ymCnOC3ijwoXOqaLKt3P1uOhgNSQUZdpjDSe+p4LUAePsMEMEDu0EgqNAbJjtUk8LNe7iYjdUbis4Pf9zg76VF75KfehlayT8vA1jWH3qYwm3sb06EtVBNdJjN6BymjPfcKaLKkliLWBDI2B9xadscN37JprIBvQ4OdbGOQoGRUhu4tA3wUm8Db7roBrHMBBOnuLojVRYXbRW/LO7PMhr8wssuxJlWO3tsmIILaGdDCx3hC1YbMt3YHTQaqXl7o6ERqQWJCdB5vXai99H651Af1/wJroWXq32/q7bXPhMRLVDHOQuYwwj4DFi7gp68XpiMKV0k2GrpAdxMOQNTX6RFpB58Lmgg7ZvUOtsfbKfZobiSoCWkOd1JLIcAcK5RBDcuLF9k3le+slEHbU4+FuQxIbwEXE2CMXGZpKUvw9/yzWH8gZivzqNF4R0rBtX2ksyfZKQ07AsnYT934oY9VXuQmUVWqUkxn5HtAGl2r+AgAiP77GI3yIJSUzxN86/sPOUh8tAVWIFSeU/bxUUGQ2HFomobrjFMtcJhWjhID/+2yJpGo1fC4qJAIq8OtXpUaA/d+t6tZ5EI9KVJK2a9qH9/LZ08+m5WMHgpE6BRHPAei9FrtuzttWSmKdtaEYkGlwq/J5fQpSZmWrnc=
  app: house-flip-tools-server
  on:
    repo: escottalexander/house-flip-tools-server
